### ISSUE TITLE
[QUESTION] How do I handle required scopes?

### ISSUE THREAD

**Issue by dialogik** [mitchwadair/tesjs#13]
**Write your question**
I have set up TESjs as described in the documentation and added ClientID and Client Secret accordingly.

```
const tes = new TES({
    identity: {
        id: process.env.TWITCH_CLIENT_ID,
        secret: process.env.TWITCH_CLIENT_SECRET
    },
    listener: {
        baseURL: process.env.BASE_URL,
        ignoreOldMessages: false
    }
});
```

And it works fine for all endpoints that don't require authentication or a specific scope. But when I try to subscribe to e.g. a subscription (which [requires the `channel:read:subscriptions` scope](https://dev.twitch.tv/docs/eventsub/eventsub-subscription-types#authorization-2)), I get the error message, that the subscription is missing proper authorization.

```
{
  error: 'Forbidden',
  status: 403,
  message: 'subscription missing proper authorization'
}                                                               
```

What is the proper way to get access to those endpoints that require authorization or specific scopes?

Thanks in advance.

**Comment by mitchwadair** [comment]
Hi!

The way Twitch's EventSub system works is that authorization is handled internally and tied to a client id.  So, you'll have to authorize your client to have access to that scope.  If you are unfamiliar with this, you can check out the doc [here](https://dev.twitch.tv/docs/authentication#introduction).

If you are using TESjs for personal use it should be as simple as using the [OAuth Implicit Code Flow](https://dev.twitch.tv/docs/authentication/getting-tokens-oauth/#oauth-implicit-code-flow).  Just build yourself a URL with your client id and localhost as your redirect uri (make sure it is registered on dev.twitch.tv for your application's OAuth Redirect URLs). 
 If you are creating a service that other people can use, you'll have to set up your authentication similarly for that as well, but with some sort of user-facing website.  Once your app has been authenticated with the correct scopes for whatever you need, it'll be good to go!

Hopefully this helps!

**Comment by dialogik** [comment]
I am (currently) just using it for my own purposes. I followed your recommendation with the implicit flow and it worked. Thanks a lot.

**Comment by mitchwadair** [comment]
Happy to help!
