### ISSUE TITLE
[RFE] Mock events using the Twitch CLI tool

### ISSUE THREAD

**Issue by dialogik** [mitchwadair/tesjs#15]
### Is your feature request related to a problem? Please describe.

When I trigger a mock event using the [Twitch CLI tool](https://github.com/twitchdev/twitch-cli)

    twitch-cli.exe event trigger subscribe -t 265345534 -F http://localhost:8080/teswh/event

I get a `[401] Request Sent` response. It would be great if this application could handle mock events coming from the CLI tool.

### Describe the solution you'd like

`[200] Success` for all mock events coming from the CLI tool, [which are currently](https://github.com/twitchdev/twitch-cli/blob/main/docs/event.md#trigger):

* `subscribe`
* `unsubscribe`
* `gift`
* `cheer`
* `transaction`
* `add-reward`
* `update-reward`
* `remove-reward`
* `add-redemption`
* `update-redemption`

### Describe alternatives you've considered

If there is no way to integrate the Twitch CLI tool, tesjs-specific commands to mock events for the CLI would be very helpful.

**Comment by mitchwadair** [comment]
This is definitely a good idea.  I'll look into this soon

**Comment by dialogik** [comment]
There are two `req.header` attributes that can be used to detect the CLI:

```
'user-agent': 'twitch-cli/0.1.0',
'twitch-eventsub-subscription-version': 'test'
```

So the `verify()` method could simply be extended to scan for these attributes. But since they could easily be faked and I could not find any header signature attributes I stopped to submit a PR. Any other ideas?

**Comment by mitchwadair** [comment]
Yeah, it is tough to allow things through based on headers alone.  I would assume that using the CLI to mock events would be only used for testing in development, so maybe including a `development` (or something similar) flag in the TESjs config could be the workaround for this problem?  That way TESjs will only accept requests with those headers in 'development' mode and ignore them when not in development mode?

This is one option, I'm going to play around with the CLI some soon as well and see if I come up with any other ideas.

**Comment by mitchwadair** [comment]
**EDIT:**
One thing you may want to try as well, is including your secret when mocking an event in the CLI using the `-s` flag.  This would make your command look something like this:
```

**Comment by mitchwadair** [comment]
Gonna close this as there hasn't been any updates for a while.  While I do think adding functionality to TESjs that would trigger events through the CLI would be nice, it seems a bit impractical to me to include in the library (and also adds a dependency for the end-user).  However, I will be adding this as part of the TESjs test suite as part of #36.  This will not change how TESjs works but will hopefully give it a more realistic/robust set of tests.

All of that said, testing using the CLI *should* work given the command input is correct (this will be verified when work on #36 is complete).  If you want to test your own application, I would suggest making a script that runs the Twitch CLI so you don't have to run commands manually each time you want to test.
