### ISSUE TITLE
[RFE] Robust handling of alternating attribute sort orders

### ISSUE THREAD

**Issue by dialogik** [mitchwadair/tesjs#18]
### Is your feature request related to a problem? Please describe.

[Since the documentation of EventSub events seem to present a different sort order than the sort order of actual EventSub responses](https://discuss.dev.twitch.tv/t/eventsub-api-documentation-inconsistency/29900) it is hard to set up events via this library. The problem is not really an issue of this library, but it makes it difficult to develop.

![Documentation vs. actual EventSub response](https://discuss.dev.twitch.tv/uploads/default/original/2X/e/ec0e98631990a6361ba063d3c89e336637092945.png)

### Describe the solution you'd like

A better handling with attributes/handle arbitrary sort orders. Some kind of automatic attribute name mapping.

### Additional information

Since this is an inconsistency with the EventSub documentation and I have reported this issue, I hope that the current problem with the Custom Points events will be solved. But it would make this library more robust against changes in the sort order of attributes. Just a nice to have!

**Comment by dialogik** [comment]
Edit: [Not really just a nice to have...](https://discuss.dev.twitch.tv/t/eventsub-api-documentation-inconsistency/29900/3)

> This is not a documentation bug really and the order of keys in the JSON blob could change at any time, as the order of keys in the object is irrelevant

**Comment by mitchwadair** [comment]
This is a good point.  If it is not guaranteed that the order of keys is the same then the best solution would probably be to just send the event object as the only argument to event handlers instead of spreading the keys as arguments.

**Comment by dialogik** [comment]
> then the best solution would probably be to just send the event object as the only argument to event handlers instead of spreading the keys as arguments.

Absolutely!

And I would keep it that way since it decreases future maintenance and improves robustness against future changes. I don't see any significant advantages by having all attributes as single arguments versus having them as attributes of the data object.

**Comment by mitchwadair** [comment]
@dialogik I just made the changes related to this RFE and it will be published to npm soon!
