### ISSUE TITLE
[QUESTION]Client-ID

### ISSUE THREAD

**Issue by SkullGaming31** [mitchwadair/tesjs#40]
**Write your question**
Im getting an error in my console.
```
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Client-ID"
    at ClientRequest.setHeader (node:_http_outgoing:576:3)
    at new ClientRequest (node:_http_client:256:14)
    at Object.request (node:https:353:10)
    at C:\Users\skullgaming31\Desktop\SkulledBot\node_modules\tesjs\lib\utils.js:16:31
    at new Promise (<anonymous>)
    at request (C:\Users\skullgaming31\Desktop\SkulledBot\node_modules\tesjs\lib\utils.js:10:16)
    at C:\Users\skullgaming31\Desktop\SkulledBot\node_modules\tesjs\lib\tes.js:144:17
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```
im not sure if its something i havnt set up up but im not using Client-ID anywhere in my code

**Additional context**
**TESjs Current Version: v0.5.1**

**Comment by mitchwadair** [comment]
Hi!  The `Client-ID` is the `id` property you set when initializing TES:
```js
const tes = new TES({
    identity: {
        id: YOUR_CLIENT_ID, <-- your client id goes here
        secret: YOUR_CLIENT_SECRET
    },
    listener: {
        baseURL: "https://example.com",
        secret: WEBHOOKS_SECRET,
    }
});
```
The error message you gave indicates that you did not include that in your TES config object (which TES should probably catch so this sort of thing doesn't happen now that I think about it).

If you do not have a client id for your project, you'll need to go create an application [here](https://dev.twitch.tv/console) and you'll receive one.

For more info on the TES configuration, you can take a look at the docs [here](https://github.com/mitchwadair/tesjs/blob/main/doc/configuration.md) which also outlines which properties are required and what types they should be, etc.

Hopefully this helps!
