### ISSUE TITLE
[RFE] When we automatically issue tokens, we want to choose a permission.

### ISSUE THREAD

**Issue by patrickmonster** [mitchwadair/tesjs#42]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when

- Normal users issue and use tokens with light privileges. 
- However, some users require events with privileges beyond this.

**Describe the solution you'd like**

- When issuing tokens automatically, why can't you set permissions?

**Describe alternatives you've considered**

- Please add "scope" permission required for token issuance.

**Additional context**

- https://dev.twitch.tv/docs/authentication/getting-tokens-oauth#oauth-client-credentials-flow

**Comment by mitchwadair** [comment]
This is similar to #13, I think you may be confused as to what the token TES uses is for.  The way EvenSub works is authorization scopes are handled internally and tied to a client id.  This means that the developer, if they require user authorization, needs to authenticate a user separately from their use of EventSub.  This authorization is then tied to the client id of the EventSub application.

The token used by TES is the app access token needed to perform EventSub-related API requests:
- [Create Subscription](https://dev.twitch.tv/docs/api/reference#create-eventsub-subscription)
- [Delete Subscription](https://dev.twitch.tv/docs/api/reference#delete-eventsub-subscription)
- [Get Subscription(s)](https://dev.twitch.tv/docs/api/reference#get-eventsub-subscriptions)

Looking at the doc for `Create Subscription` you can see what they say about it:

> Requires an app access token.
> 
> To create a subscription, you must use an app access token; however, if the subscription type requires user authorization, the user must have granted your app permissions to receive those events before you subscribe to them. For example, to subscribe to channel.subscribe events, the user must have granted your app permission which adds the channel:read:subscriptions scope to your app’s client ID.

So an RFE like this is outside the scope of TES as a library.  It is on the developer to authenticate the user outside of their use of TES.
